### ISSUE TITLE
Things to do next

### ISSUE THREAD

**Issue by nutterb** [nutterb/dbn#6]
I won't open a new issue for this each time.  I'll just keep adding checkboxes to make sure I do things in the right order (and write the appropriate documentation and tests before I move on to the next task)
- [x] review functional requirements for `model_form_to_node_form`
- [x] write tests for `model_form_to_node_form`
- [x] Write functional requirements for `dbn.formula`
- [x] Write tests for `dbn.formula`
- [x] Write functional requirements for `dbn.list`
- [x] Write tests for `dbn.list`
- [x] Figure out how to use a method internally without exporting it
- [x] Develop print method for `dbn`
- [x] Develop plot method for `dbn`

**Comment by jarrod-dalton** [comment]
This may be difficult to implement within the package, as I'm uncertain whether or not there is an API for R, but I have used this package for drawing really nice temporal Bayesian networks.

https://github.com/jluttine/tikz-bayesnet

Here's an example of what that kind of software produces:

![image](https://cloud.githubusercontent.com/assets/11472793/19988061/9e54f804-a1f4-11e6-9530-a9364a1b1e79.png)

There, you have the ability of making explicit the location of the plotted nodes. Standard algorithms in GraphViz end up putting nodes in locations that optimize some criterion, not necessarily in time order.

All this said, I do however think you have the ability to explicitly place nodes in specific locations using DiagrammeR/GraphViz.  If this is the case, then we might just line up the temporal nodes in as many vertical columns as necessary to cover all the dependencies. Something like the below diagram (which was made with PowerPoint, but you get the idea):

![image](https://cloud.githubusercontent.com/assets/11472793/19988168/31d3acb0-a1f5-11e6-829a-c020491d8e15.png)
